# Nixpacks Configuration for Railway
# This tells Railway how to build your TypeScript project

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Install ALL dependencies (Railway sets NODE_ENV=production which skips devDeps)
# We need devDependencies for TypeScript build
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npm prune --production"]

[start]
cmd = "npm start"
