# Nixpacks Configuration for Railway
# This tells Railway how to build your TypeScript project

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# TypeScript is now in regular dependencies, so standard install works
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
