# Nixpacks Configuration for Railway
# This tells Railway how to build your TypeScript project

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
# Install ALL dependencies including devDependencies (needed for TypeScript build)
# Railway sets NODE_ENV=production, so we must explicitly include dev deps
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build", "npm prune --production"]

[start]
cmd = "npm start"
