# Railway Configuration
# This file helps Railway build and deploy your app correctly

[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[deploy]
startCommand = "npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
